"use strict";
import { BaseContract, Contract, ContractFactory } from "@ethersproject-bsc/contracts";
import { BigNumber, FixedNumber } from "@ethersproject-bsc/bignumber";
import { Signer, VoidSigner } from "@ethersproject-bsc/abstract-signer";
import { Wallet } from "@ethersproject-bsc/wallet";
import * as constants from "@ethersproject-bsc/constants";
import * as providers from "@ethersproject-bsc/providers";
import { getDefaultProvider } from "@ethersproject-bsc/providers";
import { Wordlist, wordlists } from "@ethersproject-bsc/wordlists";
import * as utils from "./utils";
import { ErrorCode as errors, Logger } from "@ethersproject-bsc/logger";
////////////////////////
// Compile-Time Constants
// This is generated by "npm run dist"
import { version } from "./_version";
const logger = new Logger(version);
////////////////////////
// Exports
export { Signer, Wallet, VoidSigner, getDefaultProvider, providers, BaseContract, Contract, ContractFactory, BigNumber, FixedNumber, constants, errors, logger, utils, wordlists, 
////////////////////////
// Compile-Time Constants
version, Wordlist };
//# sourceMappingURL=ethers.js.map